#!/bin/bash

# Script is meant to be run from the top level of the Github repository.
# Script organizes raw sequencing files for samples sequenced by
# Deepali Kumar's lab. The samples were described in 
# Kumar et al. 2018, Clinical Infectious Diseases.

# Input paths.
BatchSRADownloadFASTQ="pipelines/Batch-SRADownloadFASTQ.sh"
ConsolidateRenameSRA="scripts/ConsolidateRenameSRA.sh"
clean=1 # If 0, analysis will run from beginning, overwriting existing intermediates.

# Kumar et al. 2018, Clinical Infectious Diseases
# Data for this study are unpublished and were generated by the Kumar lab.
# Flu-specific amplification was used to enrich for viral genetic material,
# and duplicate amplifications were combined for sequencing.
# We obtained the data through personal communication with Deepali
# and her lab manager, Victor.

# First, organize the appropriate metadata files.
project="flu-Kumar"
dir="nobackup/${project}/raw"
mkdir -p nobackup/${project}/raw
mkdir -p nobackup/${project}/trimmed
mkdir -p data/metadata/${project}

# Iterate through directories in which the raw data was received.
# Compile a samplesheet containing file paths and other relevant information.
while read sample
do
  # Identify the R1 and R2 sequencing files.
  R1=""
  R2=""
  for f in raw/${project}/${sample}/*R1*.fastq.gz
  do
    R1=${f}
  done
  for f in raw/${project}/${sample}/*R2*.fastq.gz
  do
    R2=${f}
  done
  # Shorten the sample name to remove the "Sample" designator
  # and strip all numerals.
  # Replace the VictorF designator with the shorter "VF" designator.
  sampleshort=${sample##*_}
  sampleshort=${sampleshort//[0-9]/}
  if [ "${sampleshort}" = "VictorF" ]; then
    sampleshort="VF"
  fi
  # Identify and pad the sample number to have three digits.
  samplenumber=${sample##*NGS}
  samplenumber=${samplenumber##*VictorF}
  samplenumber=${samplenumber##0}
  samplenumber=`printf %03d $samplenumber`
  # Combine the short sample designator with the 3-digit sample name
  # to create the sample name for our analysis.
  sampleshort=${sampleshort}${samplenumber}
  # Output the information needed to create the samplesheet.
  echo "${R1} ${R2} nobackup/${project}/trimmed/${sampleshort}_trimmed-R1.fastq.gz nobackup/${project}/trimmed/${sampleshort}_trimmed-R1.fastq.gz ${sampleshort} ${project}"
done < <( ls raw/${project} ) > data/metadata/${project}/samplesheet.txt